version: 2

models:
  - name: develop_policies_cancellation_price
    description: "Cancellation Price data"
    columns:
      - name: ID
        description: "PK and SK surrogate key"
      - name: PK
        decription: "PK from Policy table"
        data_type: VARCHAR(256)
      - name: SK
        description: "Sort key (action)"
        data_type: VARCHAR(256)
      - name: POLICY_MODIFICATION_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: COMMISSIONS
        description: ""
        data_type: VARIANT
      - name: EXPOSURE_PRICES
        description: ""
        data_type: VARIANT
      - name: FEES
        description: ""
        data_type: VARIANT
      - name: GROSS_COMMISSIONS_CHANGE
        description: ""
        data_type: FLOAT
      - name: GROSS_FEES_CHANGE
        description: ""
        data_type: FLOAT
      - name: GROSS_PREMIUM_CHANGE
        description: ""
        data_type: FLOAT
      - name: GROSS_TAXES_CHANGE
        description: ""
        data_type: FLOAT
      - name: HOLDBACKS
        description: ""
        data_type: VARIANT
      - name: NEW_GROSS_COMMISSIONS
        description: ""
        data_type: FLOAT
      - name: NEW_GROSS_FEES
        description: ""
        data_type: FLOAT
      - name: NEW_GROSS_PREMIUM
        description: ""
        data_type: FLOAT
      - name: NEW_GROSS_TAXES
        description: ""
        data_type: FLOAT
      - name: NEW_TOTAL
        description: ""
        data_type: FLOAT
      - name: TAX_GROUPS
        description: ""
        data_type: VARIANT
      - name: TOTAL_CHANGE
        description: ""
        data_type: FLOAT
  - name: develop_policyholders_locator_sk_entity
    description: "Policyholder locator entity data"
    columns:
      - name: PK
        decription: "PK from Policy table"
        data_type: VARCHAR(256)
      - name: ACCOUNT_LOCATOR
        description: "Sort key (action)"
        data_type: VARCHAR(256)
      - name: COMPLETED
        description: ""
        data_type: BOOLEAN
      - name: CREATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: FLAGS
        description: ""
        data_type: VARIANT
      - name: LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: REVISION
        description: ""
        data_type: VARCHAR(256)
      - name: UPDATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: EMAIL_ADDRESS
        description: ""
        data_type: VARCHAR(256)
      - name: FIRST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: LAST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_CITY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_COUNTRY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_COUNTY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_LOT_UNIT_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_STATE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_STREET_ADDRESS_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_ZIP_CODE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MIDDLE_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: PRIMARY_CONTACT_NUMBER
        description: ""
        data_type: VARCHAR(256)
      - name: THIRD_PARTY_NOTIFICATION_NON_CONSUMER
        description: ""
        data_type: VARCHAR(256)
      - name: TYPE_OF_INSURED
        description: ""
        data_type: VARCHAR(256)
      - name: ORGANIZATION_TYPE
        description: ""
        data_type: VARCHAR(256)
      - name: ORGANIZATION_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: POLICYHOLDER_ID
        description: ""
        data_type: VARCHAR(256)
      - name: RELATIONSHIP_ORGANIZATION
        description: ""
        data_type: VARCHAR(256)
      - name: REP_FIRST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: REP_LAST_NAME
  - name: develop_policyholders_person_sk_entity
    description: "Policyholder person entity data"
    columns:
      - name: PK
        decription: "PK from Policy table"
        data_type: VARCHAR(256)
      - name: ACCOUNT_LOCATOR
        description: "Sort key (action)"
        data_type: VARCHAR(256)
      - name: COMPLETED
        description: ""
        data_type: BOOLEAN
      - name: CREATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: FLAGS
        description: ""
        data_type: VARIANT
      - name: LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: REVISION
        description: ""
        data_type: VARCHAR(256)
      - name: UPDATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: EMAIL_ADDRESS
        description: ""
        data_type: VARCHAR(256)
      - name: FIRST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: LAST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_CITY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_COUNTRY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_COUNTY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_LOT_UNIT_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_STATE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_STREET_ADDRESS_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MAILING_ZIP_CODE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: MIDDLE_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: PRIMARY_CONTACT_NUMBER
        description: ""
        data_type: VARCHAR(256)
      - name: THIRD_PARTY_NOTIFICATION_NON_CONSUMER
        description: ""
        data_type: VARCHAR(256)
      - name: TYPE_OF_INSURED
        description: ""
        data_type: VARCHAR(256)
      - name: ORGANIZATION_TYPE
        description: ""
        data_type: VARCHAR(256)
      - name: ORGANIZATION_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: POLICYHOLDER_ID
        description: ""
        data_type: VARCHAR(256)
      - name: RELATIONSHIP_ORGANIZATION
        description: ""
        data_type: VARCHAR(256)
      - name: REP_FIRST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: REP_LAST_NAME
  - name: develop_policy_modifications
    description: "Policy modifications data"
    columns:
      - name: ID
        data_type: VARCHAR(256)
      - name: PK
        decription: "PK from Policy table"
        data_type: VARCHAR(256)
      - name: AUTOMATED_UNDERWRITING_RESULT_DECISION
        description: ""
        data_type: VARCHAR(256)
      - name: AUTOMATED_UNDERWRITING_RESULT_DECISION_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ)
      - name: AUTOMATED_UNDERWRITING_RESULT_NOTES
        description: ""
        data_type: VARIANT
      - name: CONFIG_VERSION
        description: ""
        data_type: VARCHAR(256)
      - name: CREATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: DISPLAY_ID
        description: ""
        data_type: VARCHAR(256)
      - name: EFFECTIVE_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: EXPOSURE_MODIFICATIONS
        description: ""
        data_type: VARIANT
      - name: FIELD_GROUPS_BY_LOCATOR
        description: ""
        data_type: VARIANT
      - name: FIELD_VALUES
        description: ""
        data_type: VARIANT
      - name: ISSUED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: MEDIA_BY_LOCATOR
        description: ""
        data_type: VARIANT
      - name: NAME
        description: ""
        data_type: VARCHAR(256)
      - name: NEW_POLICY_CHARACTERISTICS_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: NEW_POLICY_CHARACTERISTICS_LOCATORS
        description: ""
        data_type: VARIANT
      - name: NUMBER
        description: ""
        data_type: VARCHAR(256)
      - name: POLICY_END_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: POLICY_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: POLICYHOLDER_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: PREMIUM_CHANGE
        description: ""
        data_type: FLOAT
      - name: PREMIUM_CHANGE_CURRENCY
        description: ""
        data_type: VARCHAR(256)
      - name: PRODUCT_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: UPDATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
  - name: develop_policy_characteristics
    description: "Policy characteristics data"
    columns:
      - name: PK
        decription: "PK from Policy table"
        data_type: VARCHAR(256)
      - name: QUOTE_INCEPTION_DATE
        description: ""
        data_type: DATE
      - name: AUTO_POLICY_WITH_AGENCY
        description: ""
        data_type: VARCHAR(256)
      - name: DATE_OF_BIRTH
        description: ""
        data_type: DATE
      - name: REASON_DESCRIPTION
        description: ""
        data_type: VARCHAR(256)
      - name: REASON_CODE
        description: ""
        data_type: VARCHAR(256)
      - name: PRIOR_CARRIER_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: PRIOR_POLICY_EXPIRATION_DATE
        description: ""
        data_type: VARCHAR(256)
      - name: PRIOR_INSURANCE
        description: ""
        data_type: VARCHAR(256)
      - name: ADDITIONALINSURED_DATE_OF_BIRTH
        description: ""
        data_type: DATE
      - name: AD_LAST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: AD_FIRST_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: RELATIONSHIP_TO_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: CLAIM_AMOUNT
        description: ""
        data_type: NUMBER
      - name: CLAIM_NUMBER
        description: ""
        data_type: VARCHAR(256)
      - name: DESCRIPTION_OF_LOSS
        description: ""
        data_type: VARCHAR(256)
      - name: CLAIM_CAT
        description: ""
        data_type: BOOLEAN
      - name: CLAIM_SOURCE
        description: ""
        data_type: VARCHAR(256)
      - name: CATEGORY
        description: ""
        data_type: VARCHAR(256)
      - name: CLAIM_DATE
        description: ""
        data_type: DATE
      - name: COUNTRY
        description: ""
        data_type: VARCHAR(256)
      - name: AGENCY_PHONE_NUMBER
        description: ""
        data_type: VARCHAR(256)
      - name: EMAIL_ADDRESS
        description: ""
        data_type: VARCHAR(256)
      - name: CITY
        description: ""
        data_type: VARCHAR(256)
      - name: AGENT_ID
        description: ""
        data_type: VARCHAR(256)
      - name: LOT_UNIT
        description: ""
        data_type: VARCHAR(256)
      - name: AGENCY_CONTACT_NAME
        description: ""
        data_type: VARCHAR(256)
      - name: STATE
        description: ""
        data_type: VARCHAR(256)
      - name: AGENCY_LICENSE
        description: ""
        data_type: VARCHAR(256)
      - name: STREET_ADDRESS
        description: ""
        data_type: VARCHAR(256)
      - name: ZIP_CODE
        description: ""
        data_type: VARCHAR(256)
      - name: ANIMAL_BITE
        description: ""
        data_type: BOOLEAN
      - name: CONVICTION
        description: ""
        data_type: BOOLEAN
      - name: CANCELLATION_RENEW
        description: ""
        data_type: BOOLEAN
      - name: PREVIOUS_STREET_ADDRESS_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: PREVIOUS_COUNTRY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: PREVIOUS_ZIP_CODE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: PREVIOUS_CITY_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: PREVIOUS_LOT_UNIT_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: PREVIOUS_STATE_POLICYHOLDER
        description: ""
        data_type: VARCHAR(256)
      - name: ASSOCIATION_DISCOUNT
        description: ""
        data_type: BOOLEAN
      - name: PAPERLESS_DISCOUNT
        description: ""
        data_type: BOOLEAN
      - name: MULTI_POLICY_DISCOUNT
        description: ""
        data_type: BOOLEAN
      - name: APPLICATION_INTIATION
        description: ""
        data_type: VARCHAR(256)
      - name: INSURANCE_SCORE
        description: ""
        data_type: NUMBER
      - name: GROSS_PREMIUM
        description: ""
        data_type: DOUBLE
      - name: GROSS_PREMIUM_CURRENCY
        description: ""
        data_type: VARCHAR(256)
      - name: GROSS_TAXES
        description: ""
        data_type: DOUBLE
      - name: GROSS_TAXES_CURRENCY
        description: ""
        data_type: VARCHAR(256)
      - name: CREATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: UPDATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: CREATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: UPDATED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: END_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: ISSUED_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: MEDIA_BY_LOCATOR
        description: ""
        data_type: VARIANT
      - name: POLICY_START_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: POLICY_END_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: POLICY_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: POLICYHOLDER_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: PRODUCT_LOCATOR
        description: ""
        data_type: VARCHAR(256)
      - name: START_TIMESTAMP
        description: ""
        data_type: TIMESTAMP_TZ
      - name: TAX_GROUPS
        description: ""
        data_type: VARIANT
