
version: 2

models:
  - name: prod_signed_user_details
    description: "signed_user_details table model"
    columns:
      - name: PK
        decription: "PK from quotes table"
        data_type: VARCHAR(256)
      - name: SK
        description: "Sort key (action)"
        data_type: VARCHAR(256)
      - name: DATE
        decription: ""
        data_type: TIMESTAMP_TZ
      - name: RAW_HEADERS
        decription: ""
        data_type: VARIANT
      - name: SIGNED_NAME
        decription: ""
        data_type: VARCHAR(256)
      - name: OS
        decription: ""
        data_type: VARCHAR(256)
      - name: BROWSER
        decription: ""
        data_type: VARCHAR(256)
      - name: IP
        decription: ""
        data_type: VARCHAR(256)
      - name: DEVICE
        decription: ""
        data_type: VARCHAR(256)
      - name: POLICY_LOCATOR
        decription: ""
        data_type: FIXED
