{{ config(materialized='table') }}

select
  pk,
  sk,
  add_exposures,
  add_field_groups,
  automated_underwriting_result,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(created_timestamp)/1000)) as created_timestamp,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(created_timestamp_dynamo)/1000)) as created_timestamp_dynamo,
  documents,
  end_exposures,
  field_values,
  invoice,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(issued_timestamp)/1000)) as issued_timestamp,
  locator,
  non_renewal_description,
  non_renewal_reason,
  planned_invoices,
  policyholder_locator,
  policy_locator,
  price,
  product_locator,
  remove_field_groups,
  -- renewal_as_of_timestamp,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(renewal_end_timestamp)/1000)) as renewal_end_timestamp,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(renewal_start_timestamp)/1000)) as renewal_start_timestamp,
  socotra_document_locator,
  state,
  status,
  status_description,
  status_history,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(status_updated_timestamp)/1000)) as status_updated_timestamp,
  convert_timezone('America/New_York', to_timestamp_tz(to_number(updated_timestamp)/1000)) as updated_timestamp,
  update_exposures,
  update_field_groups,
  _fivetran_synced
from dynamodb.prod_socotra_policy_table
where (pk like 'POLICY#%' and sk like 'RENEWAL#%') and _fivetran_deleted='FALSE'
