{{ config(materialized='table') }}

	SELECT 
		QUOTE_DATE AS REPORT_DATE,
		PAYMENT_SCHEDULE_NAME,
		ISSUED_POLICY_FLAG,
		NULL AS NEW_RENEWAL,
		'USA' AS COUNTRY,
		case when f.POLICY_STATE IS NULL THEN 'Unknown' ELSE f.POLICY_STATE END AS STATE,
		CASE WHEN c.PARK_NAME IS NULL THEN 'Unknown' ELSE c.PARK_NAME END AS PARK_NAME,
		'INDIVIDUAL' AS AGENCY_CHANNEL,
		d.AGENCY_ID AS AGENCY_ID,
		CASE WHEN e.AGENCY_NAME IS NOT NULL THEN e.AGENCY_NAME ELSE 'Unknown' END AS AGENCY_CONTACT_NAME, 
		d.AGENT_ID AS AGENT_ID,
		CASE WHEN d.AGENT_ON_RECORD IS NOT NULL THEN d.AGENT_ON_RECORD ELSE 'Unknown' END AS AGENT_ON_RECORD, 
		NULL AS CANCELLATION_FLAG, 
		NULL AS CANCELLATION_DURATION,
		NULL AS CANCELLATION_DURATION_BUCKET,
		NULL AS CANCELLATION_REASON,
		NULL AS POLICY_COUNT_LOCATOR,
		A.POLICY_LOCATOR  AS QUOTE_COUNT_LOCATOR,
		NULL AS CANCELLED_POLICY_COUNT_LOCATOR,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		0 AS EARNED_PREMIUM_AMOUNT
	FROM {{ ref('QUOTE_POLICY_UPDATED') }} a
	LEFT JOIN MYSQL_DATA_MART_10001.QUOTE_EXPOSURE_CHARACTERISTICS b
	ON a.QUOTE_POLICY_LOCATOR =b.QUOTE_POLICY_LOCATOR 
	LEFT JOIN {{ ref('QUOTE_EXPOSURE_CHARACTERISTICS_FIELDS_FLATTEN') }} c
	ON b."LOCATOR"  =c.QUOTE_EXPOSURE_CHARACTERISTICS_LOCATOR 
	LEFT JOIN TRANSFORMATIONS_PROD_SOCOTRA.QUOTE_AGENCY_INFORMATION d
	ON a.QUOTE_POLICY_LOCATOR =d.QUOTE_POLICY_LOCATOR 
	AND NOT REGEXP_LIKE(D.AGENCY_ID,'[a-zA-Z]*') --d.EMAIL_ADDRESS <>'testnotifications@covertree.com'
	LEFT JOIN TRANSFORMATIONS_DYNAMODB_DEV_RAJA.DIM_AGENCY_DETAILS e
	ON (CASE 
			WHEN (D.agency_id LIKE '%MOCK%') THEN  D.agency_id
			ELSE CAST(CAST(REPLACE(D.AGENCY_ID,'C-','') AS INT) AS VARCHAR) END)=e.AGENCY_ID 
	LEFT JOIN {{ ref('QUOTE_CHARACTERISTICS') }} f
	ON a.POLICY_LOCATOR =f.POLICY_LOCATOR 
	WHERE QUOTE_DATE>='2022-01-01'
	AND QUOTE_DATE <= CURRENT_DATE()
	AND ISSUED_POLICY_FLAG=0
	GROUP BY 
		QUOTE_DATE,
		PAYMENT_SCHEDULE_NAME,
		ISSUED_POLICY_FLAG,
		case when f.POLICY_STATE IS NULL THEN 'Unknown' ELSE f.POLICY_STATE END,
		CASE WHEN c.PARK_NAME IS NULL THEN 'Unknown' ELSE c.PARK_NAME END,
		d.AGENCY_ID,
		CASE WHEN e.AGENCY_NAME IS NOT NULL THEN e.AGENCY_NAME ELSE 'Unknown' END, 
		d.AGENT_ID,
		CASE WHEN d.AGENT_ON_RECORD IS NOT NULL THEN d.AGENT_ON_RECORD ELSE 'Unknown' END,
		A.POLICY_LOCATOR