{{ config(materialized='table') }}

SELECT *,
	MONTHNAME(REPORT_DATE) AS REPORT_MONTHNAME,
	MONTH(REPORT_DATE) AS REPORT_MONTHNUMBER,
	YEAR(REPORT_DATE) AS REPORT_YEAR
FROM 
(
	SELECT 
		REPORT_DATE, 
		PAYMENT_SCHEDULE_NAME,
		ISSUED_POLICY_FLAG,
		NEW_RENEWAL,
		COUNTRY,
		STATE,
		PARK_NAME,
		AGENCY_CHANNEL,
		AGENCY_ID,
		AGENCY_CONTACT_NAME, 
		AGENT_ID,
		AGENT_ON_RECORD, 
		CANCELLATION_FLAG, 
		CANCELLATION_DURATION,
		CANCELLATION_DURATION_BUCKET,
		CANCELLATION_REASON,
		POLICY_COUNT_LOCATOR,
		QUOTE_COUNT_LOCATOR,
		GROSS_WRITTEN_PREMIUM_AMOUNT,
		GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		EARNED_PREMIUM_AMOUNT		
	FROM {{ ref('AGENCY_PERFORMANCE_ISSUED_POLICY') }} Y
	UNION ALL
	SELECT 
		REPORT_DATE, 
		PAYMENT_SCHEDULE_NAME,
		ISSUED_POLICY_FLAG,
		NEW_RENEWAL,
		COUNTRY,
		STATE,
		PARK_NAME,
		AGENCY_CHANNEL,
		AGENCY_ID,
		AGENCY_CONTACT_NAME, 
		AGENT_ID,
		AGENT_ON_RECORD, 
		CANCELLATION_FLAG, 
		CANCELLATION_DURATION,
		CANCELLATION_DURATION_BUCKET,
		CANCELLATION_REASON,
		POLICY_COUNT_LOCATOR,
		QUOTE_COUNT_LOCATOR,
		GROSS_WRITTEN_PREMIUM_AMOUNT,
		GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		EARNED_PREMIUM_AMOUNT		
	FROM {{ ref('AGENCY_PERFORMANCE_QUOTE_ISSUED') }} D
	UNION ALL
	SELECT 
		REPORT_DATE, 
		PAYMENT_SCHEDULE_NAME,
		ISSUED_POLICY_FLAG,
		NEW_RENEWAL,
		COUNTRY,
		STATE,
		PARK_NAME,
		AGENCY_CHANNEL,
		AGENCY_ID,
		AGENCY_CONTACT_NAME, 
		AGENT_ID,
		AGENT_ON_RECORD, 
		CANCELLATION_FLAG, 
		CANCELLATION_DURATION,
		CANCELLATION_DURATION_BUCKET,
		CANCELLATION_REASON,
		POLICY_COUNT_LOCATOR,
		QUOTE_COUNT_LOCATOR,
		GROSS_WRITTEN_PREMIUM_AMOUNT,
		GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		EARNED_PREMIUM_AMOUNT		
	FROM {{ ref('AGENCY_PERFORMANCE_QUOTE_NOT_ISSUED') }} 
) X