{{ config(materialized='table') }}

SELECT distinct
	a.*,
	b."TYPE",
	CASE 
		WHEN b."TYPE" ='renew' THEN Date(convert_timezone('America/New_York', to_timestamp_tz(b.ISSUED_TIMESTAMP/1000)))
		ELSE Date(convert_timezone('America/New_York', to_timestamp_tz(p.ISSUED_TIMESTAMP /1000)))
	END
	 AS POLICY_ISSUE_DATE,
	 dad.AGENCY_NAME  AS AGENCY_NAME_UPDATED,
	 DAD.AGENCY_PARENT_NAME AS AGENCY_PARENT_NAME
FROM TRANSFORMATIONS_PROD_SOCOTRA.POLICY_AGENCY_INFORMATION a
LEFT JOIN MYSQL_DATA_MART_10001.POLICY_MODIFICATION b
ON a.POLICY_MODIFICATION_LOCATOR =b."LOCATOR" 
LEFT JOIN MYSQL_DATA_MART_10001.POLICY_CHARACTERISTICS c
ON a.POLICY_CHARACTERISTICS_LOCATOR =c."LOCATOR" 
LEFT JOIN MYSQL_DATA_MART_10001.POLICY  p
ON c.POLICY_LOCATOR  = p.LOCATOR
LEFT JOIN TRANSFORMATIONS_DYNAMODB_DEV_RAJA.DIM_AGENCY_DETAILS dad 
ON (CASE 
			WHEN (a.agency_id LIKE '%MOCK%') THEN  a.agency_id
			ELSE CAST(CAST(REPLACE(a.AGENCY_ID,'C-','') AS INT) AS VARCHAR) END) = dad.AGENCY_ID
WHERE  b."TYPE" IN ('create','renew')
ORDER BY 5 DESC
