{{ config(materialized='table') }}

	SELECT distinct
		B.QUOTE_DATE AS REPORT_DATE,
		a.PAYMENT_SCHEDULE_NAME,
		EXPOSURE_NAME,
		b.ISSUED_POLICY_FLAG,
		PURCHASE_TYPE,
		COUNTRY,
		a.STATE,
		POLICY_USAGE,
		PERSONALIZED_PLAN_TYPE,
		HOME_TYPE,
		NULL AS POLICY_COUNT_LOCATOR,
		NULL AS EXPOSURE_COUNT_LOCATOR,
		B.POLICY_LOCATOR AS QUOTE_COUNT_LOCATOR,
		NULL AS CUSTOMER_BASE_COUNT_LOCATOR,
		NULL AS CANCELLED_POLICY_COUNT_LOCATOR,
		AGENCY_ID,
		AGENCY_CONTACT_NAME, 
		AGENT_ID,
		AGENT_ON_RECORD, 
		CANCELLATION_FLAG, 
		CANCELLATION_DURATION,
		CANCELLATION_DURATION_BUCKET,
		CANCELLATION_REASON,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT,
		0 AS EARNED_PREMIUM_AMOUNT,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE
	FROM {{ ref('QUOTE_POLICY_UPDATED') }} b
	LEFT JOIN {{ ref('KPI_SUMMARY_ISSUED_POLICY') }} a
	ON a.POLICY_COUNT_LOCATOR =b.POLICY_LOCATOR
	WHERE b.ISSUED_POLICY_FLAG =1
	AND a.POLICY_COUNT_LOCATOR IS NOT NULL