{{ config(materialized='table') }}

	SELECT 
		a.CANCELLATION_DATE AS REPORT_DATE,
		PAYMENT_SCHEDULE_NAME,
		EXPOSURE_NAME,
		0 AS ISSUED_POLICY_FLAG,
		CASE WHEN RENEWAL_FLAG=1 THEN 'Renew' ELSE 'New' END AS PURCHASE_TYPE,
		case when b.COUNTRY IS NULL THEN 'Unknown' ELSE b.COUNTRY END AS COUNTRY,
		case when e.POLICY_STATE IS NULL THEN 'Unknown' ELSE e.POLICY_STATE END AS STATE,
		case when b.POLICY_USAGE IS NULL THEN EXPOSURE_NAME ELSE b.POLICY_USAGE END AS POLICY_USAGE,
		case when b.PERSONALIZED_PLAN_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.PERSONALIZED_PLAN_TYPE END AS PERSONALIZED_PLAN_TYPE,
		CASE WHEN b.HOME_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.HOME_TYPE END AS HOME_TYPE,
		NULL AS POLICY_COUNT_LOCATOR,
		NULL AS EXPOSURE_COUNT_LOCATOR,
		NULL AS QUOTE_COUNT_LOCATOR,
		NULL AS CUSTOMER_BASE_COUNT_LOCATOR,
		a.POLICY_LOCATOR AS CANCELLED_POLICY_COUNT_LOCATOR,
		c.AGENCY_ID AS AGENCY_ID,
		CASE WHEN c.AGENCY_NAME_UPDATED IS NOT NULL THEN c.AGENCY_NAME_UPDATED ELSE 'Unknown' END AS AGENCY_CONTACT_NAME, 
		c.AGENT_ID AS AGENT_ID,
		CASE WHEN c.AGENT_ON_RECORD IS NOT NULL THEN c.AGENT_ON_RECORD ELSE 'Unknown' END AS AGENT_ON_RECORD, 
		A.CANCELLATION_FLAG AS CANCELLATION_FLAG,
		a.CANCELLATION_DATE,
		a.CANCELLATION_DATE -a.ISSUED_DATE AS CANCELLATION_DURATION,
		CASE 
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <0 THEN '-1'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  =0 THEN '1. Same Day'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <7 THEN '2. 1-7 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <30 THEN '3. 8-30 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <60 THEN '4. 31-60 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <90 THEN '5. 61-90 days'
			ELSE '6. 90+ days'
		END AS CANCELLATION_DURATION_BUCKET,
		CANCELLATION_REASON,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT,
		sum(GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE) AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		0 AS EARNED_PREMIUM_AMOUNT
	FROM {{ ref('POLICY_PREMIUM_AGG') }} a
	LEFT JOIN {{ ref('EXPOSURE_CHARACTERISTICS_FIELDS_FLATTEN') }} b
	ON a.EXPOSURE_CHARACTERISTICS_LOCATOR =b.EXPOSURE_CHARACTERISTICS_LOCATOR 
	LEFT JOIN {{ ref('AGENCY_DETAILS') }} c
	ON a.POLICY_LOCATOR =c.POLICY_LOCATOR  
	AND a.REPORT_DATE =c.POLICY_ISSUE_DATE 
	LEFT JOIN {{ ref('POLICY_CHARACTERISTICS') }} e
	ON a.POLICY_LOCATOR =e.POLICY_LOCATOR
	WHERE REPORT_DATE>='2022-01-01'
	AND REPORT_DATE <= CURRENT_DATE()
	AND a.CANCELLATION_FLAG=1
	GROUP BY  
		a.CANCELLATION_DATE,
		PAYMENT_SCHEDULE_NAME,
		EXPOSURE_NAME,
		CASE WHEN RENEWAL_FLAG=1 THEN 'Renew' ELSE 'New' END,
		case when b.COUNTRY IS NULL THEN 'Unknown' ELSE b.COUNTRY END,
		case when e.POLICY_STATE IS NULL THEN 'Unknown' ELSE e.POLICY_STATE END,
		case when b.POLICY_USAGE IS NULL THEN EXPOSURE_NAME ELSE b.POLICY_USAGE END,
		case when b.PERSONALIZED_PLAN_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.PERSONALIZED_PLAN_TYPE END,
		CASE WHEN b.HOME_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.HOME_TYPE END,
		a.POLICY_LOCATOR,
		c.AGENCY_ID,
		CASE WHEN c.AGENCY_NAME_UPDATED IS NOT NULL THEN c.AGENCY_NAME_UPDATED ELSE 'Unknown' END, 
		c.AGENT_ID,
		CASE WHEN c.AGENT_ON_RECORD IS NOT NULL THEN c.AGENT_ON_RECORD ELSE 'Unknown' END, 
		A.CANCELLATION_FLAG,
		a.CANCELLATION_DATE -a.ISSUED_DATE,
		CASE 
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <0 THEN '-1'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  =0 THEN '1. Same Day'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <7 THEN '2. 1-7 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <30 THEN '3. 8-30 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <60 THEN '4. 31-60 days'
			WHEN a.CANCELLATION_DATE -a.ISSUED_DATE  <90 THEN '5. 61-90 days'
			ELSE '6. 90+ days'
		END,
		CANCELLATION_REASON