{{ config(materialized='table') }}

	SELECT 
		REPORT_DATE,
		PAYMENT_SCHEDULE_NAME,
		EXPOSURE_NAME,
		1 AS ISSUED_POLICY_FLAG,
		CASE WHEN RENEWAL_FLAG=1 THEN 'Renew' ELSE 'New' END AS PURCHASE_TYPE,
		case when b.COUNTRY IS NULL THEN 'Unknown' ELSE b.COUNTRY END AS COUNTRY,
		case when e.POLICY_STATE IS NULL THEN 'Unknown' ELSE e.POLICY_STATE END AS STATE,
		case when b.POLICY_USAGE IS NULL THEN EXPOSURE_NAME ELSE b.POLICY_USAGE END AS POLICY_USAGE,
		case when b.PERSONALIZED_PLAN_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.PERSONALIZED_PLAN_TYPE END AS PERSONALIZED_PLAN_TYPE,
		CASE WHEN b.HOME_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.HOME_TYPE END AS HOME_TYPE,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN a.POLICY_LOCATOR ELSE NULL END AS POLICY_COUNT_LOCATOR,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN a.EXPOSURE_LOCATOR ELSE NULL END AS EXPOSURE_COUNT_LOCATOR,
		NULL AS QUOTE_COUNT_LOCATOR,
		NULL AS CANCELLED_POLICY_COUNT_LOCATOR,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN POLICYHOLDER_LOCATOR ELSE NULL END AS CUSTOMER_BASE_COUNT_LOCATOR,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN c.AGENCY_ID ELSE NULL END AS AGENCY_ID,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE AND c.AGENCY_NAME_UPDATED IS NOT NULL THEN c.AGENCY_NAME_UPDATED ELSE 'Unknown' END AS AGENCY_CONTACT_NAME, 
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN c.AGENT_ID ELSE NULL END AS AGENT_ID,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE AND c.AGENT_ON_RECORD IS NOT NULL THEN c.AGENT_ON_RECORD ELSE NULL END AS AGENT_ON_RECORD, 
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN A.CANCELLATION_FLAG ELSE NULL END AS CANCELLATION_FLAG, 
		NULL AS CANCELLATION_DURATION,
		NULL AS CANCELLATION_DURATION_BUCKET,
		NULL AS CANCELLATION_REASON,
--		CANCELLATION_DATE,
		SUM(GROSS_WRITTEN_PREMIUM_AMOUNT) AS GROSS_WRITTEN_PREMIUM_AMOUNT,
--		sum(GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE) AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		0 AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE,
		SUM(EARNED_PREMIUM_AMOUNT) AS EARNED_PREMIUM_AMOUNT
	FROM {{ ref('POLICY_PREMIUM_AGG') }} a
	LEFT JOIN {{ ref('EXPOSURE_CHARACTERISTICS_FIELDS_FLATTEN') }} b
	ON a.EXPOSURE_CHARACTERISTICS_LOCATOR =b.EXPOSURE_CHARACTERISTICS_LOCATOR 
	LEFT JOIN {{ ref('AGENCY_DETAILS') }} c
	ON a.POLICY_LOCATOR =c.POLICY_LOCATOR  
	AND a.REPORT_DATE =c.POLICY_ISSUE_DATE 
--	AND (CASE WHEN RENEWAL_FLAG=1 THEN a.RENEWAL_DATE ELSE a.ISSUED_DATE END) =c.POLICY_ISSUE_DATE 
	LEFT JOIN {{ ref('POLICY_CHARACTERISTICS') }} e
	ON a.POLICY_LOCATOR =e.POLICY_LOCATOR
	WHERE REPORT_DATE>='2022-01-01'
	AND REPORT_DATE <= CURRENT_DATE()
	GROUP BY 
		REPORT_DATE,
		PAYMENT_SCHEDULE_NAME,
		EXPOSURE_NAME,
		CASE WHEN RENEWAL_FLAG=1 THEN 'Renew' ELSE 'New' END,	
		case when b.COUNTRY IS NULL THEN 'Unknown' ELSE b.COUNTRY END,
		case when e.POLICY_STATE IS NULL THEN 'Unknown' ELSE e.POLICY_STATE END,
		case when b.POLICY_USAGE IS NULL THEN EXPOSURE_NAME ELSE b.POLICY_USAGE END,
		case when b.PERSONALIZED_PLAN_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.PERSONALIZED_PLAN_TYPE END,
		CASE WHEN b.HOME_TYPE IS NULL THEN EXPOSURE_NAME ELSE b.HOME_TYPE END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN a.POLICY_LOCATOR ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN a.EXPOSURE_LOCATOR ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN POLICYHOLDER_LOCATOR ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN c.AGENCY_ID ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE AND c.AGENCY_NAME_UPDATED IS NOT NULL  THEN c.AGENCY_NAME_UPDATED ELSE 'Unknown' END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN c.AGENT_ID ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE AND c.AGENT_ON_RECORD IS NOT NULL THEN c.AGENT_ON_RECORD ELSE NULL END,
		CASE WHEN REPORT_DATE=a.ISSUED_DATE THEN A.CANCELLATION_FLAG ELSE NULL END