{{ config(materialized='table') }}

SELECT 
	b."LOCATOR" AS PERIL_CHARACTERISTICS_LOCATOR,
	B.POLICY_LOCATOR,
	C.EXPOSURE_LOCATOR,
	b.EXPOSURE_CHARACTERISTICS_LOCATOR,
	c."NAME" AS PERIL_NAME,
	MAX(CASE WHEN FIELD_NAME = 'all_other_perils_deductible' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                          AS ALL_OTHER_PERILS_DEDUCTIBLE,
	MAX(CASE WHEN FIELD_NAME = 'animal_liability_limit' AND field_value<>'Excluded' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                               AS ANIMAL_LIABILITY_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'cov_a_settlement_option' THEN FIELD_VALUE END)                              AS COV_A_SETTLEMENT_OPTION,
	MAX(CASE WHEN FIELD_NAME = 'cov_b_settlement_option' THEN FIELD_VALUE END)                              AS COV_B_SETTLEMENT_OPTION,
	MAX(CASE WHEN FIELD_NAME = 'cov_c_settlement_option' THEN FIELD_VALUE END)                              AS COV_C_SETTLEMENT_OPTION,
	MAX(CASE WHEN FIELD_NAME = 'damage_to_property_of_others' THEN FIELD_VALUE END)                         AS DAMAGE_TO_PROPERTY_OF_OTHERS,
	MAX(CASE WHEN FIELD_NAME = 'debris_removal_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                                 AS DEBRIS_REMOVAL_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'earthquake_deductible' THEN FIELD_VALUE END)                                AS EARTHQUAKE_DEDUCTIBLE,
	MAX(CASE WHEN FIELD_NAME = 'equipment_breakdown_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                            AS EQUIPMENT_BREAKDOWN_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'fungi_bacteria_property_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                        AS FUNGI_BACTERIA_PROPERTY_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'identity_fraud_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                                 AS IDENTITY_FRAUD_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'inflation_guard' THEN FIELD_VALUE END)                                      AS INFLATION_GUARD,
	MAX(CASE WHEN FIELD_NAME = 'loss_assessment_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                                AS LOSS_ASSESSMENT_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'loss_of_use_percentage' THEN to_decimal(REPLACE(FIELD_VALUE,'%','')) END)   AS LOSS_OF_USE_PERCENTAGE,
	MAX(CASE WHEN FIELD_NAME = 'manufactured_home_limit' THEN FIELD_VALUE END)                              AS MANUFACTURED_HOME_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'medical_payment_to_others_limit_PerPerson' THEN FIELD_VALUE END)            AS MEDICAL_PAYMENT_TO_OTHERS_LIMIT_PERPERSON,
	MAX(CASE WHEN FIELD_NAME = 'medical_payment_to_others_limit_per_person' THEN FIELD_VALUE END)           AS MEDICAL_PAYMENT_TO_OTHERS_LIMIT_PER_PERSON,
	MAX(CASE WHEN FIELD_NAME = 'no_of_golf_carts' THEN FIELD_VALUE END)                                     AS NO_OF_GOLF_CARTS,
	MAX(CASE WHEN FIELD_NAME = 'occasional_vacation_rental' THEN FIELD_VALUE END)                           AS OCCASIONAL_VACATION_RENTAL,
	MAX(CASE WHEN FIELD_NAME = 'other_structures_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                               AS OTHER_STRUCTURES_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'personal_liability' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                                   AS PERSONAL_LIABILITY,
	MAX(CASE WHEN FIELD_NAME = 'premises_liability_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                             AS PREMISES_LIABILITY_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'residence_burglary_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                             AS RESIDENCE_BURGLARY_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'scheduled_personals' THEN FIELD_VALUE END)                                  AS SCHEDULED_PERSONALS,
	MAX(CASE WHEN FIELD_NAME = 'secondary_residence_liability_address' THEN FIELD_VALUE END)                AS SECONDARY_RESIDENCE_LIABILITY_ADDRESS,
	MAX(CASE WHEN FIELD_NAME = 'secondary_residence_liability_group' THEN FIELD_VALUE END)                  AS SECONDARY_RESIDENCE_LIABILITY_GROUP,
	MAX(CASE WHEN FIELD_NAME = 'specific_building_structure_description' THEN FIELD_VALUE END)              AS SPECIFIC_BUILDING_STRUCTURE_DESCRIPTION,
	MAX(CASE WHEN FIELD_NAME = 'spp_desc' THEN FIELD_VALUE END)                                             AS SPP_DESC,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' THEN FIELD_VALUE END)                                             AS SPP_TYPE,
	MAX(CASE WHEN FIELD_NAME = 'spp_value' THEN FIELD_VALUE END)                                            AS SPP_VALUE,
	MAX(CASE WHEN FIELD_NAME = 'unscheduled_personal_property_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                  AS UNSCHEDULED_PERSONAL_PROPERTY_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'water_backup_and_sump_overflow_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                 AS WATER_BACKUP_AND_SUMP_OVERFLOW_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'water_damage_reduced_limit' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                           AS WATER_DAMAGE_REDUCED_LIMIT,
	MAX(CASE WHEN FIELD_NAME = 'wind_hail_deductible' THEN REGEXP_REPLACE(FIELD_VALUE,'[$,]', '') END)                           		AS WIND_HAIL_DEDUCTIBLE,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =1 THEN FIELD_VALUE END)			AS SPP_TYPE1,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =2 THEN FIELD_VALUE END)			AS SPP_TYPE2,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =3 THEN FIELD_VALUE END)			AS SPP_TYPE3,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =4 THEN FIELD_VALUE END)			AS SPP_TYPE4,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =5 THEN FIELD_VALUE END)			AS SPP_TYPE5,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =6 THEN FIELD_VALUE END)			AS SPP_TYPE6,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =7 THEN FIELD_VALUE END)			AS SPP_TYPE7,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =8 THEN FIELD_VALUE END)			AS SPP_TYPE8,
	MAX(CASE WHEN FIELD_NAME = 'spp_type' AND PERIL_CHARACTERISTICS_RANK =9 THEN FIELD_VALUE END)			AS SPP_TYPE9,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =10 THEN FIELD_VALUE END)			AS SPP_TYPE10,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =1 THEN FIELD_VALUE END)			AS SPP_LIMIT1,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =2 THEN FIELD_VALUE END)			AS SPP_LIMIT2,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =3 THEN FIELD_VALUE END)			AS SPP_LIMIT3,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =4 THEN FIELD_VALUE END)			AS SPP_LIMIT4,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =5 THEN FIELD_VALUE END)			AS SPP_LIMIT5,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =6 THEN FIELD_VALUE END)			AS SPP_LIMIT6,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =7 THEN FIELD_VALUE END)			AS SPP_LIMIT7,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =8 THEN FIELD_VALUE END)			AS SPP_LIMIT8,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =9 THEN FIELD_VALUE END)			AS SPP_LIMIT9,
	MAX(CASE WHEN FIELD_NAME = 'spp_limit' AND PERIL_CHARACTERISTICS_RANK =10 THEN FIELD_VALUE END)			AS SPP_LIMIT10
FROM
	(SELECT 
		*,
		dense_rank() OVER (PARTITION BY PERIL_CHARACTERISTICS_LOCATOR,FIELD_NAME ORDER BY PARENT_LOCATOR) AS PERIL_CHARACTERISTICS_RANK
	FROM MYSQL_DATA_MART_10001.PERIL_CHARACTERISTICS_FIELDS)  a
right JOIN MYSQL_DATA_MART_10001.PERIL_CHARACTERISTICS  b
ON a.PERIL_CHARACTERISTICS_LOCATOR =b."LOCATOR" 
LEFT JOIN MYSQL_DATA_MART_10001.PERIL c
ON b.PERIL_LOCATOR =c."LOCATOR"
GROUP BY
	1,2,3,4,5
