{{ config(materialized='table') }}

SELECT 
	b.POLICY_LOCATOR,
	MAX(CASE WHEN FIELD_NAME = 'Commis_Comm_Name' THEN FIELD_VALUE END)                             AS COMMIS_COMM_NAME,
	MAX(CASE WHEN FIELD_NAME = 'Commis_Comm_Unit_ID' THEN FIELD_VALUE END)                          AS COMMIS_COMM_UNIT_ID,
	MAX(CASE WHEN FIELD_NAME = 'ad_first_name' THEN FIELD_VALUE END)                                AS AD_FIRST_NAME,
	MAX(CASE WHEN FIELD_NAME = 'ad_insured' THEN FIELD_VALUE END)                                   AS AD_INSURED,
	MAX(CASE WHEN FIELD_NAME = 'ad_last_name' THEN FIELD_VALUE END)                                 AS AD_LAST_NAME,
	MAX(CASE WHEN FIELD_NAME = 'additionalinsured_date_of_birth' THEN FIELD_VALUE END)              AS ADDITIONALINSURED_DATE_OF_BIRTH,
	MAX(CASE WHEN FIELD_NAME = 'adverse_action' THEN FIELD_VALUE END)                               AS ADVERSE_ACTION,
	MAX(CASE WHEN FIELD_NAME = 'agency_contact_name' THEN FIELD_VALUE END)                          AS AGENCY_CONTACT_NAME,
	MAX(CASE WHEN FIELD_NAME = 'agency_id' THEN FIELD_VALUE END)                                    AS AGENCY_ID,
	MAX(CASE WHEN FIELD_NAME = 'agency_information' THEN FIELD_VALUE END)                           AS AGENCY_INFORMATION,
	MAX(CASE WHEN FIELD_NAME = 'agency_license' THEN FIELD_VALUE END)                               AS AGENCY_LICENSE,
	MAX(CASE WHEN FIELD_NAME = 'agency_phone_number' THEN FIELD_VALUE END)                          AS AGENCY_PHONE_NUMBER,
	MAX(CASE WHEN FIELD_NAME = 'agent_id' THEN FIELD_VALUE END)                                     AS AGENT_ID,
	MAX(CASE WHEN FIELD_NAME = 'agent_on_record' THEN FIELD_VALUE END)                              AS AGENT_ON_RECORD,
	MAX(CASE WHEN FIELD_NAME = 'animal_bite' THEN FIELD_VALUE END)                                  AS ANIMAL_BITE,
	MAX(CASE WHEN FIELD_NAME = 'application_intiation' THEN FIELD_VALUE END)                        AS APPLICATION_INTIATION,
	MAX(CASE WHEN FIELD_NAME = 'apt_suite_other' THEN FIELD_VALUE END)                              AS APT_SUITE_OTHER,
	MAX(CASE WHEN FIELD_NAME = 'association_discount' THEN FIELD_VALUE END)                         AS ASSOCIATION_DISCOUNT,
	MAX(CASE WHEN FIELD_NAME = 'auto_policy_with_agency' THEN FIELD_VALUE END)                      AS AUTO_POLICY_WITH_AGENCY,
	MAX(CASE WHEN FIELD_NAME = 'cancellation_renew' THEN FIELD_VALUE END)                           AS CANCELLATION_RENEW,
	MAX(CASE WHEN FIELD_NAME = 'category' THEN FIELD_VALUE END)                                     AS CATEGORY,
	MAX(CASE WHEN FIELD_NAME = 'city' THEN FIELD_VALUE END)                                         AS CITY,
	MAX(CASE WHEN FIELD_NAME = 'claim_amount' THEN FIELD_VALUE END)                                 AS CLAIM_AMOUNT,
	MAX(CASE WHEN FIELD_NAME = 'claim_cat' THEN FIELD_VALUE END)                                    AS CLAIM_CAT,
	MAX(CASE WHEN FIELD_NAME = 'claim_date' THEN FIELD_VALUE END)                                   AS CLAIM_DATE,
	MAX(CASE WHEN FIELD_NAME = 'claim_number' THEN FIELD_VALUE END)                                 AS CLAIM_NUMBER,
	MAX(CASE WHEN FIELD_NAME = 'claim_source' THEN FIELD_VALUE END)                                 AS CLAIM_SOURCE,
	MAX(CASE WHEN FIELD_NAME = 'claim_status' THEN FIELD_VALUE END)                                 AS CLAIM_STATUS,
	MAX(CASE WHEN FIELD_NAME = 'claims_processing_status' THEN FIELD_VALUE END)                     AS CLAIMS_PROCESSING_STATUS,
	MAX(CASE WHEN FIELD_NAME = 'commis_comm_owner' THEN FIELD_VALUE END)                            AS COMMIS_COMM_OWNER,
	MAX(CASE WHEN FIELD_NAME = 'commissionable_partners' THEN FIELD_VALUE END)                      AS COMMISSIONABLE_PARTNERS,
	MAX(CASE WHEN FIELD_NAME = 'conviction' THEN FIELD_VALUE END)                                   AS CONVICTION,
	MAX(CASE WHEN FIELD_NAME = 'country' THEN FIELD_VALUE END)                                      AS COUNTRY,
	MAX(CASE WHEN FIELD_NAME = 'county' THEN FIELD_VALUE END)                                       AS COUNTY,
	MAX(CASE WHEN FIELD_NAME = 'date_of_birth' THEN FIELD_VALUE END)                                AS DATE_OF_BIRTH,
	MAX(CASE WHEN FIELD_NAME = 'description_of_loss' THEN FIELD_VALUE END)                          AS DESCRIPTION_OF_LOSS,
	MAX(CASE WHEN FIELD_NAME = 'document_type' THEN FIELD_VALUE END)                                AS DOCUMENT_TYPE,
	MAX(CASE WHEN FIELD_NAME = 'documents' THEN FIELD_VALUE END)                                    AS DOCUMENTS,
	MAX(CASE WHEN FIELD_NAME = 'email_address' THEN FIELD_VALUE END)                                AS EMAIL_ADDRESS,
	MAX(CASE WHEN FIELD_NAME = 'insurance_score' THEN FIELD_VALUE END)                              AS INSURANCE_SCORE,
	MAX(CASE WHEN FIELD_NAME = 'lot_unit' THEN FIELD_VALUE END)                                     AS LOT_UNIT,
	MAX(CASE WHEN FIELD_NAME = 'manual_decision' THEN FIELD_VALUE END)                              AS MANUAL_DECISION,
	MAX(CASE WHEN FIELD_NAME = 'multi_policy_discount' THEN FIELD_VALUE END)                        AS MULTI_POLICY_DISCOUNT,
	MAX(CASE WHEN FIELD_NAME = 'ncf_processing_status' THEN FIELD_VALUE END)                        AS NCF_PROCESSING_STATUS,
	MAX(CASE WHEN FIELD_NAME = 'ncf_reference_name' THEN FIELD_VALUE END)                           AS NCF_REFERENCE_NAME,
	MAX(CASE WHEN FIELD_NAME = 'ncf_status' THEN FIELD_VALUE END)                                   AS NCF_STATUS,
	MAX(CASE WHEN FIELD_NAME = 'paperless_discount' THEN FIELD_VALUE END)                           AS PAPERLESS_DISCOUNT,
	MAX(CASE WHEN FIELD_NAME = 'policy_basic_info' THEN FIELD_VALUE END)                            AS POLICY_BASIC_INFO,
	MAX(CASE WHEN FIELD_NAME = 'policy_level_suppl_uw' THEN FIELD_VALUE END)                        AS POLICY_LEVEL_SUPPL_UW,
	MAX(CASE WHEN FIELD_NAME = 'previous_address_policyholder' THEN FIELD_VALUE END)                AS PREVIOUS_ADDRESS_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_city_policyholder' THEN FIELD_VALUE END)                   AS PREVIOUS_CITY_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_country_policyholder' THEN FIELD_VALUE END)                AS PREVIOUS_COUNTRY_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_county_policyholder' THEN FIELD_VALUE END)                 AS PREVIOUS_COUNTY_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_lot_unit_policyholder' THEN FIELD_VALUE END)               AS PREVIOUS_LOT_UNIT_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_state_policyholder' THEN FIELD_VALUE END)                  AS PREVIOUS_STATE_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_street_address_policyholder' THEN FIELD_VALUE END)         AS PREVIOUS_STREET_ADDRESS_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'previous_zip_code_policyholder' THEN FIELD_VALUE END)               AS PREVIOUS_ZIP_CODE_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'prior_carrier_name' THEN FIELD_VALUE END)                           AS PRIOR_CARRIER_NAME,
	MAX(CASE WHEN FIELD_NAME = 'prior_claim_section' THEN FIELD_VALUE END)                          AS PRIOR_CLAIM_SECTION,
	MAX(CASE WHEN FIELD_NAME = 'prior_claims' THEN FIELD_VALUE END)                                 AS PRIOR_CLAIMS,
	MAX(CASE WHEN FIELD_NAME = 'prior_claims_subject_first_name' THEN FIELD_VALUE END)              AS PRIOR_CLAIMS_SUBJECT_FIRST_NAME,
	MAX(CASE WHEN FIELD_NAME = 'prior_claims_subject_last_name' THEN FIELD_VALUE END)               AS PRIOR_CLAIMS_SUBJECT_LAST_NAME,
	MAX(CASE WHEN FIELD_NAME = 'prior_insurance' THEN FIELD_VALUE END)                              AS PRIOR_INSURANCE,
	MAX(CASE WHEN FIELD_NAME = 'prior_insurance_details' THEN FIELD_VALUE END)                      AS PRIOR_INSURANCE_DETAILS,
	MAX(CASE WHEN FIELD_NAME = 'prior_policy_expiration_date' THEN FIELD_VALUE END)                 AS PRIOR_POLICY_EXPIRATION_DATE,
	MAX(CASE WHEN FIELD_NAME = 'quote_inception_date' THEN FIELD_VALUE END)                         AS QUOTE_INCEPTION_DATE,
	MAX(CASE WHEN FIELD_NAME = 'reason_cancellation_renew' THEN FIELD_VALUE END)                    AS REASON_CANCELLATION_RENEW,
	MAX(CASE WHEN FIELD_NAME = 'reason_code' THEN FIELD_VALUE END)                                  AS REASON_CODE,
	MAX(CASE WHEN FIELD_NAME = 'reason_description' THEN FIELD_VALUE END)                           AS REASON_DESCRIPTION,
	MAX(CASE WHEN FIELD_NAME = 'reference_number' THEN FIELD_VALUE END)                             AS REFERENCE_NUMBER,
	MAX(CASE WHEN FIELD_NAME = 'relationship_to_policyholder' THEN FIELD_VALUE END)                 AS RELATIONSHIP_TO_POLICYHOLDER,
	MAX(CASE WHEN FIELD_NAME = 'scope_of_claim' THEN FIELD_VALUE END)                               AS SCOPE_OF_CLAIM,
	MAX(CASE WHEN FIELD_NAME = 'state' THEN FIELD_VALUE END)                                        AS STATE,
	MAX(CASE WHEN FIELD_NAME = 'street_address' THEN FIELD_VALUE END)                               AS STREET_ADDRESS,
	MAX(CASE WHEN FIELD_NAME = 'uploaded_file' THEN FIELD_VALUE END)                                AS UPLOADED_FILE,
	MAX(CASE WHEN FIELD_NAME = 'uw_description' THEN FIELD_VALUE END)                               AS UW_DESCRIPTION,
	MAX(CASE WHEN FIELD_NAME = 'uw_details' THEN FIELD_VALUE END)                                   AS UW_DETAILS,
	MAX(CASE WHEN FIELD_NAME = 'zip_code' THEN FIELD_VALUE END)                                     AS ZIP_CODE
FROM
	MYSQL_DATA_MART_10001.POLICY_CHARACTERISTICS_FIELDS  a
LEFT JOIN MYSQL_DATA_MART_10001.POLICY_CHARACTERISTICS  b
ON a.POLICY_CHARACTERISTICS_LOCATOR  =b."LOCATOR" 
GROUP BY
	1