{{ config(materialized='table') }}

SELECT *,
	MONTHNAME(REPORT_DATE) AS REPORT_MONTHNAME,
	MONTH(REPORT_DATE) AS REPORT_MONTHNUMBER,
	YEAR(REPORT_DATE) AS REPORT_YEAR,
	CASE 
		WHEN RENEWAL_CANCELLATION_FLAG =1 THEN '4. Cancelled'	
		WHEN GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE <0 THEN '2. Downgrade'
		WHEN GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE >0 THEN '1. Upgrade'
		WHEN GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE =0 THEN '3. No Change'
		ELSE '5. Not Renewed'
	END AS POLICY_CHANGE_TYPE,
	CASE
		WHEN RENEWAL_DATE IS null THEN '7. Not Renewed'
		WHEN RENEWAL_CANCELLATION_DATE IS null THEN '7. Not Cancelled'
		WHEN RENEWAL_CANCELLATION_DATE -RENEWAL_DATE  =0 THEN '1. Same Day'
		WHEN RENEWAL_CANCELLATION_DATE -RENEWAL_DATE  <7 THEN '2. 1-7 days'
		WHEN RENEWAL_CANCELLATION_DATE -RENEWAL_DATE  <30 THEN '3. 8-30 days'
		WHEN RENEWAL_CANCELLATION_DATE -RENEWAL_DATE  <60 THEN '4. 31-60 days'
		WHEN RENEWAL_CANCELLATION_DATE -RENEWAL_DATE  <90 THEN '5. 61-90 days'
		ELSE '6. 90+ days'
	END AS CANCELLATION_DURATION_BUCKET,
	CASE WHEN UPCOMING_RENEWAL_FLAG =1 THEN
		CASE 
			WHEN REPORT_DATE -CURRENT_DATE()  =0 THEN '1. TODAY'
			WHEN REPORT_DATE -CURRENT_DATE()  <7 THEN '2. 1-7 days'
			WHEN REPORT_DATE -CURRENT_DATE()  <30 THEN '3. 8-30 days'
			WHEN REPORT_DATE -CURRENT_DATE()  <60 THEN '4. 31-60 days'
			WHEN REPORT_DATE -CURRENT_DATE()  <90 THEN '5. 61-90 days'
			ELSE '6. 90+ days' 	
		END
		WHEN RENEWAL_FLAG=1 THEN '7. Renewed'
		ELSE '8.Not Renewed'
	END AS UPCOMING_RENEWAL_BUCKET,
	CASE WHEN RENEWAL_FLAG=1 THEN
		CASE 
			WHEN RENEWAL_DATE - REPORT_DATE <0 THEN '1. Before Policy End'
			WHEN RENEWAL_DATE - REPORT_DATE  =0 THEN '2. Same Day as Policy End'
			WHEN RENEWAL_DATE - REPORT_DATE  <7 THEN '3. 1-7 days'
			WHEN RENEWAL_DATE - REPORT_DATE  <30 THEN '4. 8-30 days'
			WHEN RENEWAL_DATE - REPORT_DATE  <60 THEN '5. 31-60 days'
			WHEN RENEWAL_DATE - REPORT_DATE  <90 THEN '6. 61-90 days'
			ELSE '7. 90+ days' 	
		END
		ELSE '8. Not Renewed'
	END AS RENEWAL_DURATION_BUCKET
FROM
(
SELECT xx.*,
	PC.POLICY_STATE,
	dpd.CANCELLATION_DATE AS RENEWAL_CANCELLATION_DATE,
	dpd.CANCELLATION_REASON AS RENEWAL_CANCELLATION_REASON,
	CASE WHEN dpd.CANCELLATION_DATE IS NOT NULL THEN 1 ELSE 0 END AS RENEWAL_CANCELLATION_FLAG,
	CASE WHEN REPORT_DATE >= CURRENT_DATE() THEN 1 ELSE 0 END AS UPCOMING_RENEWAL_FLAG
FROM (
SELECT 
	POLICY_END_DATE+1 AS REPORT_DATE,
	LEAD(ISSUED_DATE) OVER (PARTITION BY POLICY_LOCATOR ORDER BY POLICY_START_DATE) AS RENEWAL_DATE,
	*,
	CASE WHEN POLICY_LOCATOR = lead(POLICY_LOCATOR) OVER (ORDER BY POLICY_LOCATOR,ISSUED_DATE) THEN 1 ELSE 0 end AS RENEWAL_FLAG,
	COALESCE(LEAD(GROSS_WRITTEN_PREMIUM_AMOUNT) OVER (PARTITION BY POLICY_LOCATOR ORDER BY POLICY_START_DATE),0) AS GWP_RENEWAL,
	LEAD(GROSS_WRITTEN_PREMIUM_AMOUNT) OVER (PARTITION BY POLICY_LOCATOR ORDER BY POLICY_START_DATE) - GROSS_WRITTEN_PREMIUM_AMOUNT AS GROSS_WRITTEN_PREMIUM_AMOUNT_CHANGE
from(
SELECT 
	ISSUED_DATE,
	POLICY_START_DATE,
	POLICY_END_DATE,
	a.CANCELLATION_FLAG,
	a.CANCELLATION_REASON,
--	CASE WHEN RENEWAL_FLAG = 1 THEN 'Renew' ELSE 'New' END AS NEW_RENEW,
	POLICY_LOCATOR,
	sum(GROSS_WRITTEN_PREMIUM_AMOUNT) AS GROSS_WRITTEN_PREMIUM_AMOUNT
FROM {{ ref('POLICY_PREMIUM_GROSS_WRITTEN_v2') }} a
GROUP BY 
	ISSUED_DATE,
	POLICY_START_DATE,
	POLICY_END_DATE,
	CANCELLATION_FLAG,
	CANCELLATION_REASON,
--	CASE WHEN RENEWAL_FLAG = 1 THEN 'Renew' ELSE 'New' END,
	POLICY_LOCATOR
) x
) xx
LEFT JOIN {{ ref('DIM_POLICY_DURATION') }} dpd
ON xx.POLICY_LOCATOR=dpd.POLICY_LOCATOR 
AND xx.RENEWAL_DATE=dpd.POLICY_ISSUED_DATE
LEFT JOIN {{ ref('POLICY_CHARACTERISTICS') }} PC 
ON xx.POLICY_LOCATOR=PC.POLICY_LOCATOR 
) xxx
WHERE CANCELLATION_FLAG=0
ORDER BY 
	POLICY_LOCATOR,
	ISSUED_DATE