{{ config(materialized='table') }}

SELECT 
	a.POLICY_LOCATOR,
	max(STATE) AS POLICY_STATE,
	max(PERSONALIZED_PLAN_TYPE) AS POLICY_PLAN_TYPE
FROM {{ ref('QUOTE_EXPOSURE_CHARACTERISTICS_FIELDS_FLATTEN_STAGE1') }} a
GROUP BY a.POLICY_LOCATOR
