{{ config(materialized='table') }}

SELECT 
	QUOTE_POLICY_LOCATOR,
	POLICY_LOCATOR,
	POLICYHOLDER_LOCATOR, 
	PAYMENT_SCHEDULE_NAME,
	QUOTE_DATE,
	ISSUED_TIMESTAMP,
	CREATED_TIMESTAMP,
	STATE,
	CASE WHEN ISSUED_TIMESTAMP IS NULL THEN 0 ELSE 1 END AS ISSUED_POLICY_FLAG
FROM (
SELECT
	LOCATOR AS QUOTE_POLICY_LOCATOR,
	POLICY_LOCATOR,
	POLICYHOLDER_LOCATOR,
	PAYMENT_SCHEDULE_NAME,
	ISSUED_TIMESTAMP,
--		Date(convert_timezone('America/New_York', to_timestamp_tz(CASE WHEN ISSUED_TIMESTAMP IS NULL THEN CREATED_TIMESTAMP ELSE ISSUED_TIMESTAMP END /1000))) AS QUOTE_DATE,
	Date(convert_timezone('America/New_York', to_timestamp_tz(CREATED_TIMESTAMP/1000))) AS QUOTE_DATE,
	CREATED_TIMESTAMP,
	STATE,
	CASE WHEN ISSUED_TIMESTAMP IS NULL THEN 0 ELSE 1 END AS ISSUED_POLICY_FLAG,
	rank() over(PARTITION BY POLICY_LOCATOR ORDER BY ISSUED_POLICY_FLAG desc,CREATED_TIMESTAMP DESC) AS policy_rank
FROM MYSQL_DATA_MART_10001.QUOTE_POLICY 
ORDER BY 1 ASC,3
)X
WHERE policy_rank=1