
version: 2

models:
  - name: develop_quotes
    description: "quotes table model"
    columns:
      - name: PK
        decription: "PK from quotes table"
        data_type: VARCHAR(256)
      - name: SK
        description: "Sort key (action)"
        data_type: VARCHAR(256)
      - name: CREATED_AT
        data_type: FIXED
        description: ""
      - name: DESCRIPTION
        data_type: VARCHAR(256)
        description: ""
      - name: POLICY_LOCATOR
        data_type: VARCHAR(256)
        description: ""
      - name: QUOTE_LOCATOR
        data_type: VARCHAR(256)
        description: ""
      - name: STATUS
        data_type: VARCHAR(256)
        description: ""
      - name: UPDATED_AT
        data_type: FIXED
        description: ""
      - name: CONVERTED
        data_type: BOOLEAN
        description: ""
